name: Build FFmpeg
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
          
      - name: Install dependencies
        run: sh -x dependencies.sh
        
      - name: Move source code
        run: cp -av ./ffmpeg/* ./
          
      - name: Configure FFmpeg
        run: ./configure --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --enable-gpl --enable-nonfree --enable-gnutls --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265
        
      - name: Build FFmpeg
        run: make
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg
          path: ffmpeg.exe