name: Build FFmpeg
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
          
      - name: Install dependencies
        run: sh -x dependencies.sh
        
      - name: Move source code
        run: mv -v ./ffmpeg/* ./
          
      - name: Configure FFmpeg
        run: sh -x configure-build.sh
        
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ffbuild config log
          path: ffbuild/config.log
        
      - name: Build FFmpeg
        run: make
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg
          path: ffmpeg