name: Build latest FFmpeg
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
          
      - name: Install dependencies
        run: ./dependencies.sh
        
      - name: Move helpers
        run: mv -v ./ffmpeg-windows-build-helpers/* ./
          
      - name: Compile FFmpeg
        run: ./cross_compile_ffmpeg.sh --ffmpeg-source-dir=$GITHUB_WORKSPACE/ffmpeg-source --gcc-cpu-count=2 --disable-nonfree=n --sandbox-ok=y --compiler-flavors=win64
          
      - name: Upload FFmpeg with FDK AAC
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-win64-nonfree
          path: ffmpeg-source/ffmpeg.exe
          
      - name: Upload FFmpeg GPL
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-win64-gpl
          path: ffmpeg-source/bin/ffmpeg.exe
          
      - name: Upload FFplay with FDK AAC
        uses: actions/upload-artifact@v2
        with:
          name: ffplay-win64-nonfree
          path: ffmpeg-source/ffplay.exe
          
      - name: Upload FFplay GPL
        uses: actions/upload-artifact@v2
        with:
          name: ffplay-win64-gpl
          path: ffmpeg-source/bin/ffplay.exe
          
      - name: Upload x264
        uses: actions/upload-artifact@v2
        with:
          name: x264-win64
          path: sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/bin/x264.exe
          
      - name: Upload x264 all bitdepth
        uses: actions/upload-artifact@v2
        with:
          name: x264-win64-all-bitdepth
          path: sandbox/win64/x264_all_bitdepth/x264.exe
          
      - name: Upload x265
        uses: actions/upload-artifact@v2
        with:
          name: x265-win64
          path: sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/bin/x265.exe
          
      - name: Upload x265 all bitdepth
        uses: actions/upload-artifact@v2
        with:
          name: x265-win64-all-bitdepth
          path: sandbox/win64/x265_all_bitdepth/8bit/x265.exe