name: Build FFmpeg
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
          
      - name: Install dependencies
        run: |
          chmod +x dependencies.sh
          ./dependencies.sh
        
      - name: Move helpers
        run: mv -v ./ffmpeg-windows-build-helpers/* ./
          
      - name: Compile FFmpeg
        run: ./cross_compile_ffmpeg.sh --ffmpeg-source-dir=./ffmpeg-source --gcc-cpu-count=2 --disable-nonfree=n --sandbox-ok=y --compiler-flavors=win64
          
      - name: Upload artifact 1
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg1
          path: ffmpeg/ffmpeg.exe
          
      - name: Upload artifact 2
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ffmpeg1
          path: ffmpeg/win64/ffmpeg.exe
          
      - name: Upload artifact 3
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ffmpeg2
          path: ffmpeg.exe
          
      - name: Upload artifact 4
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ffmpeg3
          path: sandbox/ffmpeg.exe