name: Build FFmpeg
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
          
      - name: Move source code
        run: mv -v ./ffmpeg-windows-build-helpers/* ./
          
      - name: Compile FFmpeg
        run: sh -x cross_compile_ffmpeg.sh --ffmpeg-source-dir=ffmpeg --disable-nonfree=n --sandbox-ok=y --compiler-flavors=win64 --debug
          
      - name: Upload artifact 1
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg1
          path: ffmpeg.exe
          
      - name: Upload artifact 2
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg2
          path: ffmpeg/ffmpeg.exe
          
      - name: Upload artifact 3
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg3
          path: sandbox/ffmpeg.exe